#  menu items
[[main]]
  name = "Billing"
  weight = 6
  url = "https://my.terohost.com"

[[main]]
  name = "Game Panel"
  weight = 5
  url = "https://panel.terohost.com"

[[main]]
  name = "Discord"
  weight = 4
  url = "https://discord.terohost.com"

[[main]]
  name = "Docs"
  weight = 3
  url = "/docs/"

